### PR TITLE
[WIP] Migrate to neutrino v9

### PR DESCRIPTION
**Pull request by helfi92**

### CODE REVIEW

**Comment by edmorley** [comment]
IMO `neutrino-preset-mozilla-frontend-infra` is an unnecessary extra layer of over-complexity/indirection that should be deprecated and not used any more, particularly now that Neutrino supports many of these things natively. I would strongly recommend not using it in taskcluster/taskcluster-web-server#47.

**Comment by edmorley** [comment]
Another downside to using a shared preset like this, is that it pulls in every dependency for different types of projects, even though most won't be used:
https://github.com/mozilla-frontend-infra/neutrino-preset-mozilla-frontend-infra/blob/874b6f86689a2959fdf09f0b83042d2d806e834e/package.json#L13-L31

**Comment by helfi92** [comment]
@edmorley The goal of `neutrino-preset-mozilla-frontend-infra` was so that mozillians can quickly start hacking on new projects while maintaining somewhat of a consistency across Mozilla projects. If we do deprecate this repo, how do you suggest we maintain the consistency?

**Comment by edmorley** [comment]
I agree consistency is a good thing to aim for, however:
* Neutrino's presets are meant to achieve that - if we're missing a feature, or choosing suboptimal defaults - then let's add it upstream, now that we have more active maintenance there
* it's currently very very hard for people not familiar with webpack/Neutrino/... (which was myself until a year ago) to understand how things are configured when there are so many layers of abstraction (it's easy to forget this when we're both now familiar). For example when using this repo, a project's config comprises:
  - their own `.neutrinorc.js
  - a selection of the the 15-20 different middleware in this repo (and to work out which I have to manually follow the require() trails)
  - the top level Neutrino presets (eg `@neutrinojs/react`)
  - any sub-presets those depend on (eg `@neutrinojs/web`, `@neutrinojs/html-template`)
  - webpack 4 defaults/concepts
* some types of config really should be project-specific. ie: this repo makes very opinionated (and non-standard) linting choices, which I don't think are necessarily appropriate for all projects. (Sticking to standard AirBnb or Prettier makes more sense IMO; "exceptions to the rule" are somewhat contrary to the Prettier mentality)
* with webpack 4/babel 7/the new Neutrino 9 features, many part of this preset are now redundant. eg:
  - [devtool.js](https://github.com/mozilla-frontend-infra/neutrino-preset-mozilla-frontend-infra/blob/874b6f86689a2959fdf09f0b83042d2d806e834e/devtool.js): replaced by the `devtool` web preset option (and the node preset already sets a sourcemap, so doesn't need it)
  - [local-modules.js](https://github.com/mozilla-frontend-infra/neutrino-preset-mozilla-frontend-infra/blob/874b6f86689a2959fdf09f0b83042d2d806e834e/local-modules.js): this is a really bad idea - overriding the default modules resolution causes lots of hard to debug issues, which is why we removed it from upstream
  - [decorators.js](https://github.com/mozilla-frontend-infra/neutrino-preset-mozilla-frontend-infra/blob/874b6f86689a2959fdf09f0b83042d2d806e834e/decorators.js): The decorators spec still isn't stabilised (it's stage 3) and has had several breaking changes, which is why the React team are not recommending its usage yet (see various issues on CRA repo). If specific projects want to take that risk, fair enough, but let's not introduce something risky to all users, when many will not be familiar with the downsides.
  - [react-components-es5.js](https://github.com/mozilla-frontend-infra/neutrino-preset-mozilla-frontend-infra/blob/874b6f86689a2959fdf09f0b83042d2d806e834e/react-components-es5.js): Presuming this just adds "compile down to ES5" support, then this is fixed upstream.
  - [rhl.js](https://github.com/mozilla-frontend-infra/neutrino-preset-mozilla-frontend-infra/blob/874b6f86689a2959fdf09f0b83042d2d806e834e/rhl.js): support for react-hot-loader 4 has been added upstream
  - [stage.js](https://github.com/mozilla-frontend-infra/neutrino-preset-mozilla-frontend-infra/blob/874b6f86689a2959fdf09f0b83042d2d806e834e/stage.js): this should be converted to use the lint-staged CLI (given the Neutrino evolution), at which point it's not Neutrino specific, so doesn't really belong in this repo
  - [versioning.js](https://github.com/mozilla-frontend-infra/neutrino-preset-mozilla-frontend-infra/blob/874b6f86689a2959fdf09f0b83042d2d806e834e/versioning.js): this cache busting should not be required, and is also not compatible with Neutrino 9

**Comment by helfi92** [comment]
Thanks for elaborating, this was really helpful. I will go ahead and deprecate the repo.

**Comment by edmorley** [comment]
No worries - sorry for not giving the longer version initially :-)

**Pull request closed without merging**
